### ISSUE TITLE
Low performance without TTA

### ISSUE THREAD

**Issue by Joshua1225** [SILI1994/rotation-invariant-pointcloud-analysis#1]
Hi. Thank you for sharing codes and resources.
I have a question about your method without test-time augmentation.
How to reproduce it on the Modelnet40 dataset？
I only got 82-83 percent accuracy with the pretrained checkpoint, compared to 90.2 reported.

**Comment by feiran-l** [comment]
Hi there. It would require to trained from scratch with TTA disabled. My apology that we haven't recorded that checkpoint as it is not the primary result.

**Comment by Joshua1225** [comment]
All right. Thanks.
